#test:
#    path: /test
#    controller: App\Controller\SecurityController::testAction
index:
    path: /
    controller: App\Controller\ProfileController::index


analytics:
    path: /analytics
    controller: App\Controller\ProfileController::analytics
#registration:
#    resource: App\Controller\RegistrationController
#    type:     annotation
#scurity:
#    resource: App\Controller\SecurityController
#    type:     annotation


register:
    path: /register
    controller: App\Controller\RegistrationController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

change_password:
    path: /password/change
    controller: App\Controller\SecurityController::changePassword

change_password_request:
    path: /password/request
    controller: App\Controller\SecurityController::changePasswordRequest

change_password_confirm:
    path: /password/reset/{token}
    controller: App\Controller\SecurityController::changePasswordConfirm

enable_account:
    path: /account/enable/{token}
    controller: App\Controller\SecurityController::confirmAccount

logout:
    path: /logout

homepage:
    path: /
    controller: App\Controller\ProfileController::indexAction

router:
    path:     /check
    controller: App\Controller\SecurityController::routerAction

bill_index:
    path: /bills
    controller: App\Controller\BillController::index

bill_new:
    path: /bills/new
    controller: App\Controller\BillController::new

bill_new_for_place:
    path: /bills/{place}/new
    controller: App\Controller\BillController::newBillForPlace

bill_show:
    path: /bills/{id}
    controller: App\Controller\BillController::show

bill_edit:
    path: /bills/{id}/edit
    controller: App\Controller\BillController::edit

bill_delete:
    path: /bills/{id}/delete
    controller: App\Controller\BillController::delete

bill_delete_file:
#    path: /bills/{id}/file/delete
    path: /bills/file/{file}
    controller: App\Controller\BillController::deleteFile

bill_toggle_payment:
    path: /bills/payment/{id}
    controller: App\Controller\BillController::togglePayment

place_index:
    path: /places
    controller: App\Controller\PlaceController::index

my_places:
    path: /myplaces
    controller: App\Controller\PlaceController::myPlaces

place_new:
    path: /places/new
    controller: App\Controller\PlaceController::new

my_place_new:
    path: /myplaces/new
    controller: App\Controller\PlaceController::myNew

place_show:
    path: /places/{id}
    controller: App\Controller\PlaceController::show

place_edit:
    path: /places/{id}/edit
    controller: App\Controller\PlaceController::edit

place_delete:
    path: /places/{id}/delete
    controller: App\Controller\PlaceController::delete

user_index:
    path: /users
    controller: App\Controller\UserController::index

user_new:
    path: /users/new
    controller: App\Controller\UserController::new

user_show:
    path: /users/{id}
    controller: App\Controller\UserController::show

user_edit:
    path: /users/{id}/edit
    controller: App\Controller\UserController::edit

user_delete:
    path: /users/{id}/delete
    controller: App\Controller\UserController::delete

meter_index:
    path: /meters
    controller: App\Controller\MeterController::index

meter_new:
    path: /meters/new
    controller: App\Controller\MeterController::new

meter_new_for_place:
    path: /meters/{place}/new
    controller: App\Controller\MeterController::newMeterForPlace

meter_show:
    path: /meters/{id}
    controller: App\Controller\MeterController::show

meter_edit:
    path: /meters/{id}/edit
    controller: App\Controller\MeterController::edit

meter_delete:
    path: /meters/{id}/delete
    controller: App\Controller\MeterController::delete


indication_index:
    path: /indications
    controller: App\Controller\IndicationController::index

indication_new:
    path: /indications/new
    controller: App\Controller\IndicationController::new

indication_new_for_meter:
    path: /indications/{meter}/new
    controller: App\Controller\IndicationController::newIndicationForMeter

indication_show:
    path: /indications/{id}
    controller: App\Controller\IndicationController::show

indication_edit:
    path: /indications/{id}/edit
    controller: App\Controller\IndicationController::edit

indication_delete:
    path: /indications/{id}/delete
    controller: App\Controller\IndicationController::delete

indication_delete_file:
    path: /indications/{id}/file/delete
    controller: App\Controller\IndicationController::deleteFile
###
tariff_index:
    path: /tariffs
    controller: App\Controller\TariffController::index

tariff_new:
    path: /tariffs/new
    controller: App\Controller\TariffController::new

tariff_new_for_meter:
    path: /tariff/{meter}/new
    controller: App\Controller\TariffController::newTariffForMeter

tariff_show:
    path: /tariffs/{id}
    controller: App\Controller\TariffController::show

tariff_edit:
    path: /tariffs/{id}/edit
    controller: App\Controller\TariffController::edit

tariff_delete:
    path: /tariffs/{id}/delete
    controller: App\Controller\TariffController::delete

###
tariff_type_index:
    path: /tarifftypes
    controller: App\Controller\TariffTypeController::index

tariff_type_new:
    path: /tarifftypes/new
    controller: App\Controller\TariffTypeController::new

tariff_type_new_for_user:
    path: /tarifftypes/{userObject}/new
    controller: App\Controller\TariffTypeController::newForUser

tariff_type_show:
    path: /tarifftypes/{id}
    controller: App\Controller\TariffTypeController::show

tariff_type_edit:
    path: /tarifftypes/{id}/edit
    controller: App\Controller\TariffTypeController::edit

tariff_type_delete:
    path: /tariff-type/{id}/delete
    controller: App\Controller\TariffTypeController::delete

tariff_type_and_tariff_new:
    path: /tariff-type-and-tariff/{id}/new
    controller: App\Controller\TariffTypeController::newTariffTypeAndTariffForMeter


####

profile:
    path: /profile
    controller: App\Controller\ProfileController::profile
picture:
    path: /user/{user}/profile/picture
    controller: App\Controller\ProfileController::changePicture


